# Generated by Django 5.1.4 on 2024-12-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_attendance_is_delete_attendance_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='early_by',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_by',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='direction',
            field=models.CharField(choices=[('Check In', 'Check In'), ('Check Out', 'Check Out'), ('Personal In', 'Personal In'), ('Personal Out', 'Personal Out')], max_length=100),
        ),
    ]
