# Generated by Django 5.1.4 on 2024-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_attendance_early_by_attendance_late_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='direction',
            field=models.CharField(choices=[('Check In', 'Check In'), ('Check Out', 'Check Out'), ('Personal Out', 'Personal Out'), ('Personal In', 'Personal In')], max_length=100),
        ),
    ]
