# Generated by Django 5.1.4 on 2024-12-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0004_alter_attendance_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='early_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_by',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='direction',
            field=models.CharField(choices=[('Check In', 'Check In'), ('Check Out', 'Check Out')], max_length=100),
        ),
    ]
